version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Marcus Compiling the Go code...
      - go build hello.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello
